services:
  blog-app:
    image: 'rhoopoe/blog-site:latest'
    build:
      dockerfile: ./Dockerfile
    container_name: blog-app
    depends_on:
      - blog-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blog-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - /home/$USER/blog:/blog-data
  blog-db:
    image: 'postgres:15-alpine'
    container_name: blog-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres