logging:
    level:
        org:
            springframework:
                security: TRACE
server:
    error:
        include-message: always
spring:
    datasource:
        password: jIOHohfdoiHIAD445_jds#LLd
        url: jdbc:postgresql://localhost:5432/personal_site
        username: rhoopoe
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
