logging:
    level:
        org:
            springframework:
                security: TRACE
spring:
    h2:
        console.enabled: true
    datasource:
        url: jdbc:h2:mem:database
        username: sa
        password: password
        driverClassName: org.h2.Driver
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: h2
app:
    constants:
        file-root: src/main/resources
        image-location:
            post-picture: /images/post-pictures
            thumbnail: /images/thumbnails
        image-processing:
            thumbnail:
                height: 200
                width: 200
            post-picture:
                height: 300
                width: 1600
        host: http://localhost:8080
        client: http://localhost:5173
        secrets:
            jwt-secret-key: 56bd52a9882a6b7bfd065c980907a4e656bd52a9882a6b7bfd065c980907a4e6
            username: rhoopoe
            password: ateitiesprofesionalas